spring:
  application:
    name: academy
  datasource:
    url: jdbc:mysql://localhost:3306/sqc_management?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations: classpath:db/migration
    validate-on-migrate: true
    enabled: true
    baseline-on-migrate: true
